"
"	author:liushiyao
"	create_time:2017年12月25日
"
"

syntax on	"自动语法高亮"
set number	"显示行号"
set autoindent 	"把当前行的对齐格式应用到下一行"
set tabstop=4	"设置TABLE为4个空格"
set history=100 "设置历史记录"
set showmatch	"高亮显示匹配的括号"
"set cursorline	"突显当前行"
set enc=utf-8	"设置编码方式"
set ruler         " show the cursor position all the time
set cursorline cursorcolumn 
set nocompatible "去掉讨厌的有关vi一致性模式，避免以前版本的一些bug和局限"
"高亮主题

syntax enable "开启语法高亮
"molokai solarized
colorscheme molokai 


"Nerd Tree
let NERDChristmasTree=0
let NERDTreeWinSize=40
let NERDTreeChDirMode=2
let NERDTreeIgnore=['\~$', '\.pyc$', '\.swp$']
let NERDTreeShowBookmarks=1
let NERDTreeWinPos="left"
autocmd vimenter * if !argc() | NERDTree | endif         " Automatically open a NERDTree if no files where specified
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif " Close vim if the only window left open is a NERDTree
nmap <F5> :NERDTreeToggle<cr>




"Neocomplete
"Note: This option must be set in .vimrc(_vimrc).  NOT IN .gvimrc(_gvimrc)!
" Disable AutoComplPop.
let g:acp_enableAtStartup = 0
" Use neocomplete.
let g:neocomplete#enable_at_startup = 1
" Use smartcase.
let g:neocomplete#enable_smart_case = 1
" Set minimum syntax keyword length.
let g:neocomplete#sources#syntax#min_keyword_length = 1

" Define dictionary.
let g:neocomplete#sources#dictionary#dictionaries = {
    \ 'default' : '',
    \ 'vimshell' : $HOME.'/.vimshell_hist',
    \ 'scheme' : $HOME.'/.gosh_completions'
        \ }



" Local config
if filereadable($HOME . "/.vimrc.local")
  source ~/.vimrc.local
endif

"加载插件配置文件
if filereadable(expand("~/.vimrc.bundles"))
  source ~/.vimrc.bundles
endif


